#!/bin/bash

msg() { echo "GROWROOT:" "$@" ; }
fail() { [ $# -eq 0 ] || msg "$@"; exit 1; }

# Resolve device node from a name.  This expands any LABEL or UUID.
# $1=name
# Resolved name is echoed.
resolve_device() {
        DEV="$1"

        case $DEV in
        LABEL=*)
                DEV="${DEV#LABEL=}"

                # support any / in LABEL= path (escape to \x2f)
                case "${DEV}" in
                */*)
                if command -v sed >/dev/null 2>&1; then
                        DEV="$(echo ${DEV} | sed 's,/,\\x2f,g')"
                else
                        if [ "${DEV}" != "${DEV#/}" ]; then
                                DEV="\x2f${DEV#/}"
                        fi
                        if [ "${DEV}" != "${DEV%/}" ]; then
                                DEV="${DEV%/}\x2f"
                        fi
                        IFS='/'
                        newroot=
                        for s in $DEV; do
                                newroot="${newroot:+${newroot}\\x2f}${s}"
                        done
                        unset IFS
                        DEV="${newroot}"
                fi
                esac
                DEV="/dev/disk/by-label/${DEV}"
                ;;
        UUID=*)
                DEV="/dev/disk/by-uuid/${DEV#UUID=}"
                ;;
        esac
        # Only canonicalise if a valid file, in case $DEV isn't a filename
        [ -e "$DEV" ] && DEV=$(readlink -f "$DEV")
        echo "$DEV"
}

export ROOT=
for x in $(cat /proc/cmdline); do
        case $x in
        root=*)
                ROOT=${x#root=}
                ROOT=$(resolve_device "$ROOT")
                ;;
        esac
done

{ [ ! -L "${ROOT}" ] && rootdev=${ROOT} || rootdev=$(readlink -f "${ROOT}") ; } ||
        fail "failed to get target of link for ${ROOT}"

case "${rootdev}" in
        *[0-9]) : ;;
        # the root is a disk, not a partition (does not end in a digit)
        # no need to do anything in this case, kernel already knows the full size.
    *) exit 0;;
esac

# remove all consective numbers from the end of rootdev to get 'rootdisk'
rootdisk=${rootdev}
while [ "${rootdisk%[0-9]}" != "${rootdisk}" ]; do
        rootdisk=${rootdisk%[0-9]};
done
partnum=${rootdev#${rootdisk}}

# if the basename of the root device (ie 'xvda1' or 'sda1') exists
# in /sys/block/ then it is a block device, not a partition
# (xen xvda1 is an example of such a funny named block device)
# echo "rootdev: ${rootdev} ${rootdev##*/}"
[ -e "/sys/block/${rootdev##*/}" ] && exit 0

growpart ${rootdisk} ${partnum} && partprobe && resize2fs ${rootdev}
exit 0
